server:
  port: 8050
  forward-headers-strategy: framework
spring:
  application:
    name: sms-service
  config:
    import: "aws-parameterstore:"
aws:
  paramstore:
    prefix: /scheduler
    name: scheduler-demo




