server:
  port: 8765
spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  client:
    service-url:
      defatul-zone: http://localhost:8761/eureka