server:
  port: 8000
spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  client:
    service-url:
      defatul-zone: http://localhost:8761/eureka
logging:
  level:
    root: INFO
    org.springframework.security: TRACE

