server:
  port: 8765
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
#        PDF SERVICE
        - id: pdf-service
          uri: lb://pdf-service
          predicates:
            - Path=/pdf/**
          filters:
            - RewritePath=/pdf/(?<path>.*), /$\{path}
#       CURRENCY EXCHANGE SERVICE
        - id: currency-exchange-service
          uri: lb://currency-exchange
          predicates:
            - Path=/currency-exchange/**
          filters:
            - RewritePath=/currency-exchange/(?<path>.*), /$\{path}
#        SMS SERVICE
        - id: sms-service
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
          filters:
            - RewritePath=/sms/(?<path>.*), /$\{path}
#        STRIPE INTEGRATION
        - id: stripe-integration-service
          uri: lb://stripe-integration-service
          predicates:
            - Path=/stripe-integration/**
          filters:
            - RewritePath=/stripe-integration/(?<path>.*), /$\{path}
#         STATISTICS
        - id: statistics-service
          uri: lb://statistics-service
          predicates:
            - Path=/statistics/**
          filters:
            - RewritePath=/statistics/(?<path>.*), /$\{path}
##############################################################################
        # Open api endpoint
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
###############################################################################


  #      routes:
  #        - id: get
  #          uri: http://httpbin.org:80
  #          predicates:
  #            - Path=/get/**
  #          filters:
  #            - RewritePath=/get/(?<path>.*), /$\{path}
  #            - AddRequestHeader=Hello, World
  #        #            - name: RequestRateLimiter
  #        #              args:
  #        #                redis-rate-limiter.replenishRate: 1
  #        #                redis-rate-limiter.burstCapacity: 60
  #        #                redis-rate-limiter.requestedTokens: 15
  #        - id: rewritepath_route
  #          uri: https://example.org
  #          predicates:
  #            - Path=/red/**
  #          filters:
  #            - RewritePath=/red(?<segment>/?.*), $\{segment}
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  client:
    service-url:
      defatul-zone: http://localhost:8761/eureka