version: '3.7'

services:
  redis:
    image:  redis:6.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: always
    volumes:
      - ./logs:/log
      - ./conf:/conf
