CREATE TABLE currency_exchange
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    currency_from       VARCHAR(50),
    currency_to         VARCHAR(50),
    conversion_multiple DECIMAL,
    CONSTRAINT pk_currencyexchange PRIMARY KEY (id)
);