server:
  port: 8020
spring:
  application:
    name: security-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-server:9000/auth2/jwks
logging:
  level:
    root: INFO
    org.springframework.security: TRACE
#      roles: USER