spring:
  application:
    name: multiple-service
  config:
    import: optional:configserver:http://localhost:8888
  redis:
    host: localhost
    password: redis
    port: 6379
    database: 0

server:
  port: 8200

eureka:
  client:
    service-url:
      defatul-zone: http://localhost:8761/eureka