spring:
  application:
    name: multiple-service
server:
  port: 8200
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  client:
    service-url:
      defatul-zone: http://localhost:8761/eureka