server:
  port: 8200
spring:
  application:
    name: multiple-service
  config:
    import: optional:configserver:http://localhost:8888
  redis:
    host: localhost
    password: redis
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: currencyInfo
#    consumer:
#      group-id: OfficeGroupId
#      auto-offset-reset: latest
eureka:
  client:
    service-url:
      defatul-zone: http://localhost:8761/eureka