server:
  port: 8200
spring:
  application:
    name: multiple-service
  config:
    import: optional:configserver:http://localhost:8888
  redis:
    host: localhost
    password: redis
    port: 6379
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: localhost:9092
      acks: -1
      client-id: conversion-multiple-service
    template:
      default-topic: currencyInfo1

eureka:
  client:
    service-url:
      defatul-zone: http://localhost:8761/eureka


