spring:
  application:
    name: currency-exchange
  config:
    import: optional:configserver:http://localhost:8888
  liquibase:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    change-log: classpath:db/migrations/db.changelog-master.yaml
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: testuser
    password: password
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      #liqubase will handle all migrations
      ddl-auto: none
    defer-datasource-initialization: false
  h2:
    console:
      enabled: true
server:
  port: 8000
logging:
  level: debug